### ISSUE TITLE
Content fix: Need to update content in card

### ISSUE THREAD

**Issue by Jaspreet099** [hekors/hacktoberfest-with-hekors#6]
It should be reach out
![image](https://user-images.githubusercontent.com/75212002/195998850-d47d55b8-7b52-4f04-914e-a49e90f1b1a8.png)

**Comment by yashsehgal** [comment]
Thanks for working on this issue @Jaspreet099 🚀

**Comment by yashsehgal** [comment]
Code changes are reverted and merged ✅
